name:                dep-one
version:             0.1.0.0
github:              "kadoban/test-dep-one"
license:             BSD3
author:              "Joshua Simmons"
maintainer:          "joshua.simmons@emptypath.com"
copyright:           "2017 Joshua Simmons"

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Nonsense dependency to test some junk

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
